//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseImageManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\AutoTestFiles\\WebAdmin\\Screenshots")]
        public string BaseImageFolder {
            get {
                return ((string)(this["BaseImageFolder"]));
            }
            set {
                this["BaseImageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastOpenFolder {
            get {
                return ((string)(this["LastOpenFolder"]));
            }
            set {
                this["LastOpenFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxHistory {
            get {
                return ((int)(this["MaxHistory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxQuickAccess {
            get {
                return ((int)(this["MaxQuickAccess"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenOnStart {
            get {
                return ((bool)(this["OpenOnStart"]));
            }
            set {
                this["OpenOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExitAfterApply {
            get {
                return ((bool)(this["ExitAfterApply"]));
            }
            set {
                this["ExitAfterApply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Workspace\\BSI\\WAResultImageIndex.xml")]
        public string DefaultIndexFile {
            get {
                return ((string)(this["DefaultIndexFile"]));
            }
            set {
                this["DefaultIndexFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\WebAdminTest\TestResult\333_03_31_2014\WebAdmin_SH\WAResultImageIndex.xml</string>
  <string>C:\WebAdminTest\TestResult\332_03_30_2014\WebAdmin_SH\WAResultImageIndex.xml</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HistoryFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HistoryFiles"]));
            }
            set {
                this["HistoryFiles"] = value;
            }
        }
    }
}
